image: docker:latest
services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apk update
  - apk upgrade
  - apk add bash

stages:
  - build

build-php:
  stage: build
  script:
    - ./build.sh
