image: docker:latest
services:
  - docker:dind

variables:
  BUILD_VERSION: '8.0'
  BUILD_TARGET: 'php'

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY


stages:
  - build
  - push


build:
  stage: build
  script:
    - docker build --build-arg PHP_VERSION=$BUILD_VERSION --target=$BUILD_TARGET --pull -t $CI_REGISTRY_IMAGE:$BUILD_VERSION .

push:
  stage: push
  script:
    - docker push $CI_REGISTRY_IMAGE:$BUILD_VERSION
