name: php images publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  

jobs:

  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [7.4, 8.0]
        target: [fpm, tester]
    
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push php${{matrix.version}}-${{matrix.target}}
      uses: docker/build-push-action@v2
      with:
        push: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tags: ${{matrix.version}}-${{matrix.target}}
        targets: ${{matrix.target}}
        build-args: |
          PHP_VERSION="${{matrix.version}}"
